# Generated by Django 4.2.6 on 2023-10-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='zipcode',
        ),
    ]
