# Generated by Django 4.2.6 on 2023-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_doctor_address_remove_doctor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Surgery', 'Surgery'), ('Oncology', 'Oncology')], max_length=100),
        ),
    ]
