# Generated by Django 4.2.6 on 2023-10-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_bed_room_inpatient_bed_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illness_id', models.IntegerField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
                ('illness_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.illness')),
            ],
        ),
    ]
