# Generated by Django 4.2.6 on 2023-10-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_illness_illness_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.doctor'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='illness_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.illness'),
            preserve_default=False,
        ),
    ]
