# Generated by Django 4.2.6 on 2023-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_inpatient_doctor_medicalhistory_illness_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
