# Generated by Django 4.2.6 on 2023-10-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_inpatient_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpatient',
            name='treatment_type',
            field=models.CharField(choices=[('General', 'General'), ('Surgery', 'Surgery')], default='General', max_length=20),
        ),
    ]
